### ISSUE TITLE
Breadcrumb Navigation - Artikel-ID festlegen nav->setArticleId(42);

### ISSUE THREAD

**Issue by alexplusde** [RexDude/navigation_factory#11]
Hi RexDude,

Im Moment keine Option, der rex_breadcrumb_nav() einen Parameter zu geben, wenn man die Brotkrümel-Navigation eines fremden Artikels einfügen will. Den Anwendungsfall habe ich allerdings gerade.

Ich habe selbst was dazu gebaut, allerdings nicht als PR, denn ich bin da auf ein merkwürdiges Verhalten von Redaxo gestoßen:

[PasteBin](http://pastebin.com/pSpFfrks
)
- In Zeile 50-52 habe ich setArticleId hinzugefügt.
- In Zeile 77-83 setze ich die ArticleId.
- In Zeile 91, 93 und 122 habe ich $REX['article_id'] durch $articleId ersetzt.

Das merkwürdige findet in Zeile 79/80 statt: In $REX habe ich normalerweise ja nicht den Pfad (z.B. |7|12|18|) zu **fremden** Artikeln. Sobald ich aber

```
			$art = OOArticle::getArticleById($articleId, 0);
			$art->getParentTree();
```

einfüge, ohne, dass ich mit $art noch etwas mache, kann ich auch in $REX auf den Pfad zugreifen. ich hätte erwartet, dass ich auf jeden Fall in Zeile 91 bei 

```
$path = explode('|', $REX['ART'][$this->articleId]['path'][$REX['CUR_CLANG']] . $this->articleId);
```

etwas ändern muss. Das fühlt sich für mich irgendwie nicht sauber an, nur 
```
			$art = OOArticle::getArticleById($articleId, 0);
			$art->getParentTree();
```
einfügen zu müssen und dann passiert ein bisschen Magie und das wars.

Falls es doch genügt, kannst du's gerne übernehmen.

**Comment by RexDude** [comment]
Hmm weiss auch nicht. Da es ein spezieller Sonderfall ist würd ich hier nix weiter machen.

**Comment by alexplusde** [comment]
Klar, kein Problem. 

Mich hat vor allem das erstaunt, wieso $REX befüllt wird, wenn ich einen Artikel ansteure. Aber das ist halt dann so.

**Comment by RexDude** [comment]
Ich glaube das wird da alles gecachet in $REX u.a..
