### ISSUE TITLE
FOR

### ISSUE THREAD

**Issue by Hirbod** [RexDude/navigation_factory#16]
Hi Rudi,

willst du deine AddOn auch nach FOR ziehen, oder willst du alles als One-Man-Show betreiben?

LG
Hirbod

**Comment by RexDude** [comment]
addon bleibt erstmal hier. one man show ist absolut der falsche begriff wenn man mal schaut wieviele hier mitgewirkt haben.
LG

**Comment by Hirbod** [comment]
Umso eher macht es Sinn, es nach FOR zu transferieren.
https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io

Ließ mal die REPO-Readme. Du wirst keinerlei "Macht" über deine AddOns verlieren, bleibst auch LEAD und Hauptentscheider. Ich denke, es macht Sinn.

**Comment by RexDude** [comment]
Also die Idee mit FOR find ich super. Momentan zieht es mich da aber nicht hin. Aber ich geb dir sofort bescheid wenn es sich ändern sollte bzw. du bekommst es ja dann eh mit.
