### ISSUE TITLE
has-sub muss zur li nicht zur ul ;)

### ISSUE THREAD

**Issue by RexDude** [RexDude/navigation_factory#2]
Codebeispiele + Changelog etc. auch korrigieren

**Comment by alexwenz** [comment]
+1

**Comment by RexDude** [comment]
Kannst dus lösen? ;)

**Comment by RexDude** [comment]
@alexwenz 
Deine Lösung war leider buggy. Habs jetzt per dom parser einfach gelöst :)

**Comment by alexwenz** [comment]
Hi Dude. Alles klar. Dankeschön. Kannst Du kurz erläutern, warum es buggy war?

**Comment by RexDude** [comment]
Ich hatte die REDAXO Demo hergenommen und daran getestet. Die has-sub Klasse wurde auch an Lis gehängt bei mir die gar keine ul darunter hatten.

![hassub](https://cloud.githubusercontent.com/assets/2674480/11526845/91371678-98dd-11e5-9b33-f049dceb73d5.png)

Vielen Dank aber für deinen Einsatz!!!

**Comment by alexwenz** [comment]
Danke für die Info. Das ist natürlich seltsam. Bei mir läuft das problemlos mit meiner Version. Sachen gibts.

Einsatz: zumindest mal versucht habe ich es ;-) Vielleicht kommt ja irgendwann mal was brauchbares...

**Comment by RexDude** [comment]
Egal....hauptsache jetzt gehts. Und ich bin ganz happy die Simple Dom Lösung gefunden zu haben. Damit kann man auch nachträglich sehr einfach seine Navi parsen und mit Zusätzen bestücken, siehe Readme der 1.1.0.
