### ISSUE TITLE
Vorschlag: Optionsänderung

### ISSUE THREAD

**Issue by JeGr** [RexDude/navigation_factory#3]
Ahoi,

da ich gerade ein neues Projekt entwickle und das Template Vorgabe ist, habe ich gerade noch rechtzeitig mitbekommen, dass es in den letzten Tagen ein Update von SEO42/Nav42 gab und das nun ein extra Projekt ist. Toll :+1: 

Was mich gerade stört/behindert ist, dass sowohl bei der normalen Navigation als auch bei Breadcrumbs es nicht möglich ist, das umschließende Element zu verändern bzw. eines hinzuzufügen.

Bei Breadcrumbs bspw. habe ich gerade ein Template, dass sehr stark HTML5 umsetzt und auch diverse Tags nutzt (nav, section etc.). Hier wird eine BC Navigation mit geschachteltem

    <section>
      <p>
        <a href="link">text</a>
        <a href="link">text</a>
        text
      </p>
    </section>

absolut sauber und schick gelöst. Leider kann ich das nicht mit der Nav Breadcrumb Klasse abbilden, da hier immer von einer Liste ausgegangen wird.

Da der Listtype auch erst im letzten "getNavigation" gesetzt wird, kann ich hier auch nichts einfach überschreiben ohne die ganze Klasse nochmal abzuleiten, was ich als etwas overkill empfinde.

Daher Vorschlag:

setOrderedList(true)  ->  setListElement(string) ändern und das dann per default eben auf "ul" oder "ol" setzen. Damit ist es problemlos möglich zwischen Listen, aber auch in einen simplen "p" oder anderen Tag zu switchen ohne jedes Mal die ganze Klasse mit allen Funktionen abzuleiten.

Wäre definitiv ein Live-Saver in einigen Templates, wo ich Seo42+Nav42 extrem gerne einsetze! :)

Grüße
-jens

**Comment by RexDude** [comment]
Hey,

kannst du mal posten wie deine Breadcrumb ausgabe aussehen soll/muss? Oder hast du das schon?

**Comment by JeGr** [comment]
Siehe oben :) Die Section + P + A Kombination ist das Breadcrumb. OK, die Section hat noch 2 Klassen für Aktivierung als Breadcrumb und für das Styling (section class="breadcrumb pattern05a") aber ansonsten ist es das schon.

**Comment by RexDude** [comment]
Und was machst du dann z.b. mit den Li's die rex_breadcrumb_nav mit ausspuckt?

**Comment by JeGr** [comment]
Aaah ich sehe das Problem, ich hatte vergessen, dass dann natürlich die LIs ebenso angepasst werden müssen. Hmm in meinem Fall wären das dann einfach A's bzw. wenn in den LI's schon A's drin sind, einfach "nichts" (also weglassen). Wobei das ja einfach abzufragen ist, da es in HTML nur zwei Listenelemente gibt. Und wenn das ListElement nicht ol oder ul ist, dann wird das LI unterdrückt. :) Andere Option wäre das ebenfalls überschreibbar zu machen, dann hätte man auch gleich eine Möglichkeit bspw. span's drumherum zu packen (was ich auch schon in Templates gesehen habe).

**Comment by RexDude** [comment]
Hmm ich denk mal drüber nach. Aber hier wird halt langsam die Grenzen überschritten hin zu einfach einer eigen Entwicklung. Weil ich weiss net ob mans jeden Recht machen kann und soll.

**Comment by RexDude** [comment]
Ein P herzunehmen ist semantisch übrigens net optimal finde ich. Warum machst du das eigentlich und nimmst nicht einfach eine ul/ol?

**Comment by JeGr** [comment]
Dadurch, dass man die Optionen bzw. die Schalter auf dem Default belässt, ändert sich ja nichts, die Klasse an sich wird aber flexibler ohne dass man gleich seine eigene Forken oder Ableiten muss und das finde ich im Sinne der Updatefähigkeit des Addons schon sehr positiv. Natürlich ist es abzuwägen (von deiner Seite) ob das Sinn macht, allerdings sehe ich die Änderungen nicht so tiefgreifend an, als dass diese zu Wildwuchs führen und dass eine Navigation irgendwann bei HTML5 nicht mehr zwingend eine Liste ist, ist denke ich ein Weg der sich abzeichnet (und Sinn macht). Genauso wie in den 90ern irgendwann die Tabelle als Formatierungstool von DIVs und Co. abgelöst wurde :)

Vielleicht kannst du dir das mal anschauen:
https://github.com/JeGr/navigation_factory

Ich hab da gerade mal quick & dirty einen Fork mit heißer Nadel editiert (ohne das LI jetzt flexibel zu machen) einfach um zu zeigen was ich mein(t)e bevor du schon geantwortet hattest ;)

Edit: Zur zweiten Frage: wie eingangs gesagt ist das Template nicht meine Erfindung sondern festgelegt weil es von einer Agentur eingekauft wurde und die hat das in Hinblick auf HTML5 eben so entwickelt. Ob an der Stelle nun ein P oder DIV semantisch schöner wäre ist natürlich wieder diskutabel, dass sie es mit NAV und SECTIONs gelöst haben, allerdings nicht unüblich. Notfalls kann ich versuchen das in was anderes abzuwandeln, aber ein UL/OL ist hier einfach unnötig, weil kein LI benötigt wird, das A innerhalb ist schon entsprechend formatiert (inline block mit background etc. und Abstand zum nächsten Element).

**Comment by JeGr** [comment]
BTW: Der Fork war vorauseilender Gehorsam, weil du mir sonst immer auf Feature Requests antwortest, ich soll doch nen PR schicken, deshalb wollte ich diesmal vorbereitet sein :grinning:

**Comment by RexDude** [comment]
Also ich würd halt einfach das Template abändern und den Code verbessern an der Stelle :P

**Comment by RexDude** [comment]
Feature Request ist schon erstmal gut und wenn approved dann gerne einen PR ;)

**Comment by JeGr** [comment]
Jein, wie gesagt, die LIs sind ja überflüssig und ein 30kb CSS will ich an der Stelle nicht noch komplett neu aufrollen. Ist eher kontraproduktiv gerade. Deshalb das Feature mal ansprechen und den Fork zum Demonstrieren was ich meinte.

**Comment by RexDude** [comment]
Hmm also da es wirklich ein Spezialfall ist und normal niemand sonst auf die kommen sollte hier keine ul/ol zu verwenden hab ich wenig Motivation das reinzunehmen. Sorry :)

**Comment by RexDude** [comment]
Leit dir doch die Klasse kurz ab oder kopier sie, schmeiss den ganzen Kram raus auch dazu und bau dir kurz deine eigene Braedcrumb nav.

**Comment by RexDude** [comment]
Ups falscher Knopf :D

**Comment by RexDude** [comment]
Und schick dem Template Bauer ne Mail: bitte in zukunft so machen: http://getbootstrap.com/components/#breadcrumbs

**Comment by JeGr** [comment]
Naja ich bin mir nicht sicher, dass das so "speziell" ist. Einige Seiten definieren Breadcrumb Markup mit Divs und A, also nicht unähnlich zu meinem Fall:

https://css-tricks.com/navigation-in-lists-to-be-or-not-to-be/
Siehe listless nav

Wir hatten die Diskussion intern auch schon, es wird eben beides genutzt. Und nicht jeder macht alles nach Bootstrap. Das Ding ist zwar schön, aber eben kein offizieller Standard.

**Comment by RexDude** [comment]
Hmm ok. Wie wäre es mit einem setListlessMode(true) was das ul entfernt und auch die lis?

**Comment by RexDude** [comment]
Oder besser setListMode(false)

**Comment by JeGr** [comment]
Hmm klingt interessant. Was wird dann ausgegeben? Nur Link und Text? Wäre keine schlechte Methode :+1:

**Comment by RexDude** [comment]
deine section und p und was du noch alles willst kannst du dann herumwrappen wie du willst von hand.

**Comment by RexDude** [comment]
Ja nur link und text. viel mehr bleibt ja nicht mehr übrig.
könnte man dann auch für die anderens navs sogar einführen :)

**Comment by JeGr** [comment]
Jau, die Section und der Absatz ist ist kein Problem. Je mehr ich drüber nachdenke umso mehr gefällts mir :)

**Comment by RexDude** [comment]
Ich baus mal eben ein :)

**Comment by JeGr** [comment]
Dann hau ich mal meinen Fork weg ;)

**Comment by RexDude** [comment]
Bitte mal testen :)

**Comment by JeGr** [comment]
Gerade kurz eingebaut - sieht gut aus :+1: :)

**Comment by RexDude** [comment]
Optimal. Dann viel Spaß damit ;)

**Comment by JeGr** [comment]
Besten Dank :smile:

**Comment by RexDude** [comment]
Kein Problem. Gut das du so hartnäckiig geblieben bist. Der Link hat mich überzeugt. Und die jetzige Lösung passt für mich auch :)

**Comment by JeGr** [comment]
Super :smiley: 
Finde es schön wenn man so zum Konsens kommt.

Andere kleine Frage am Rande: Kann ich die normale Navigation (nicht breadcrumb) sinnvoll überschreiben/ändern, um bspw. statt ul/li/a kombination ein select/option/nur_text zu erreichen ohne gleich ne ganze Navigation neu zu bauen? Hintergrund ist die mobile Navigation für Smartphones etc. die dann als pulldown angezeigt wird. Irgendwie ists entweder zu spät oder ich steh auf dem Schlauch wie das "schön" zu machen ist ;)

**Comment by RexDude** [comment]
Also es ist ganz einfach: wenn die Änderungen nur minimal von der jetzigen Ausgabe abweichen könnte mans versuchen in die bestehende Klasse so wie setListMode() einzuführen. Ansonsten eigenes Ding machen, klasse ableiten und gewünschte Stellen überschreiben.

**Comment by RexDude** [comment]
Was auch ne Option ist: diese neue Klasse dann mitliefern zum Addon wenn da draussen auch andere sowas brauchen können. Z.B. könnte man mal ne rex_boostrap_dropdown_nav machen vielleicht irgendwann die dann mit eingehängt wird.

**Comment by JeGr** [comment]
Nur damit du verstehst was ich meine, so sieht bspw. diese doppelte Menüführung aus, das Option-Menü wird ausgeblendet solange die Display Size nicht unterschritten wird. Sobald das Layout bemerkt, dass die Breite < %wert ist und anfängt, das responsive Zeugs anzuziehen, wird die normale Nav ab- und die Sec-Nav angeschaltet:

    <nav class="mainmenu">
      <ul>
        <li class="current-menu-item"><a href="index.html">Home</a></li>
        <li><a href="contact.html">Kontakt</a></li>
      </ul>
      <select id="sec-nav" name="sec-nav">
        <option value="#">Main Menu</option>
        <option value="index.html" selected="selected">Home</option>
        <option value="contact.html">Kontakt</option>
      </select>
    </nav>

**Comment by RexDude** [comment]
Hmm noch ne "neue" Art seine Nav zu bauen. Wobei mir die selctboxen noch nie gefallen haben für Mobile Ansatz. Heute macht man das doch auch noch kaum oder? ;) Du siehst das Spielchen beginnt von vorne ;)

Naja wenn man wieder Steuern könnte: statt ul/li select/option kannst du dass mit 2 nav objekten hintereinander ausgegeben hinbekommen. wobei noch net geklärt ist wie die submenu verschatelung ausschauen soll. oder halt einfach ne zusätzliche klasse rex_select_nav und dann 1 rex_nav und ein rex_select_nav Objekt nutzen.

**Comment by JeGr** [comment]
Ich denke der Ansatz mit eigener Klasse ist da vielversprechender als das ändern der normalen Nav Klasse :)

"Neu" ist die Art sicher nicht (denke ich), wenn man auf Template Seiten wie bspw. themeforest.net vorbei schaut, findet man hauptsächlich zwei Stile: das "Hamburger-Menü" (drei horizontale Streifen als Button) mit PopUp was sich als Liste abbilden lässt wie eben auch das Select/Option Menü. Mir gefällt optisch auch ersteres besser, funktional sind beide ;)

Aber mal schauen wie ich das irgendwie hinbasteln kann, momentan findet mein müder Kopf den Ansatz irgendwie nicht :dizzy_face:

**Comment by RexDude** [comment]
"Neu" für mich ;) Weil noch nie gebraucht :P
Vielleicht neues Issue eröffnen...evtl. wärs wirklich nur ein Schalter in der rex_nav.

**Comment by JeGr** [comment]
Na gut, wenn du meinst ;)
