### ISSUE TITLE
Nav-Klasse anpassen oder ergänzen für mobile/responsive Templates

### ISSUE THREAD

**Issue by JeGr** [RexDude/navigation_factory#4]
Wie gewünscht, neuer Issue für den Fall einer alternativen/zusäztlichen Navigation bei responsive Layouts, die das mobile navigieren mittels Select/Option Kombination realisieren. Beispiel:

```
<nav class="mainmenu">
  <ul>
    <li class="current-menu-item"><a href="index.html">Home</a></li>
    <li><a href="contact.html">Kontakt</a></li>
  </ul>
  <select id="sec-nav" name="sec-nav">
    <option value="#">Main Menu</option>
    <option value="index.html" selected="selected">Home</option>
    <option value="contact.html">Kontakt</option>
  </select>
</nav>
```

Menüebenen werden hier nicht durch geschachtelte ULs realisiert, sondern via Prefix vor dem Text:

```
Main Menu
Home
Beispiel-Ebene
- Unterpunkt
- Unterpunkt
-- Unterpunkt des Unterpunkts
Kontakt
```

Scheint mir aber als zusätzliche Klasse evtl. einfacher realisierbar (auch wegen Prefix definierbar für Untermenüs).

Grüße :)

**Comment by RexDude** [comment]
> Scheint mir aber als zusätzliche Klasse evtl. einfacher realisierbar (auch wegen Prefix definierbar für Untermenüs).
Stimmt. Muss man mal in Ruhe durchdenken. Weiss net ob Prefix wirklich änder bar sein muss. Aber vielleicht schon.m Manche wollen evtl. Leerzeichen als Prefix-Zeichen.

**Comment by JeGr** [comment]
Oder ein nbsp bspw., deshalb finde ich die Idee als zusätzliche "kleine" Klasse wie die breadcrumb Navi recht charmant.

**Comment by JeGr** [comment]
Kurze Frage: Bist du zu innerer Einsicht und Erkenntnis gelangt, ob und/oder wie man das implementieren kann/sollte? Da ich gerade aktiv an so einem Projekt arbeite wo es benötigt wird, kann ich ggf. ein klein wenig beisteuern.

**Comment by RexDude** [comment]
> Kurze Frage: Bist du zu innerer Einsicht und Erkenntnis gelangt, ob und/oder wie man das implementieren kann/sollte? 

Ja und zwar eigene Klasse. Ableiten weiss ich nicht obs sinn macht weil man ja dann alle eigenschaften mituieht die man eigentlich überhaupt nicht braucht. Klasse würde ich rex_select_nav nennen. Struktur sollte wie bei den anderen Klassen sein. getNavigation() gibts dann wieder aus.

> Da ich gerade aktiv an so einem Projekt arbeite wo es benötigt wird, kann ich ggf. ein klein wenig beisteuern.

Äh ich steuer hier nix bei in nächster Zeit, d.h. du musst 100% übernehmen. Rückfragen sind aber erlaubt.

> Und im Redaxo Forum ist ja scheinbar auch schon jemand auf das Problem gestoßen:

Jein, sie sprichtzwar von der select nav meint aber was anderes damit glaub ich.

**Comment by JeGr** [comment]
> Ja und zwar eigene Klasse. (...) rex_select_nav

Ich kanns gern versuchen auch wenn ich etwas unsicher bin, wie/wo am Besten anzusetzen. Da der Select/Option Krams recht simpel gehalten sein sollte, würde ich da fast die breadcrumb nav Klasse als Basis nehmen, da hier noch nicht so viel Zeugs mit enthalten ist.

> Äh ich steuer hier nix bei in nächster Zeit, d.h. du musst 100% übernehmen. Rückfragen sind aber erlaubt.

Rückfragen hier erlaubt? Oder via welchem Weg? Da ich selten irgendwelche AddOns ergänze (auch wenn ich Lust dazu habe ;)) ... 

> Jein, sie spricht zwar von der select nav meint aber was anderes damit glaub ich.

Deshalb meinte ich artverwandt, aber man sieht, dass auch bei ihr select/option als mobile Navigation zum Einsatz kommt, somit ist das ganze "Projektchen" dann immerhin keine Wanderdüne... ehm Einzelfall. :) Es hilft also wenigstens nicht nur mir :+1:

**Comment by RexDude** [comment]
Mach ne neue Klasse und orentier die beim Aufbau an der rex_braedcrum_nav. und jetzt leg los... ;)

**Comment by RexDude** [comment]
Es gibt jetzt ne rex_custom_nav. Das kann man als Schablone nehmen für seine Custom Navi :)
