### ISSUE TITLE
Sitemap Navigation

### ISSUE THREAD

**Issue by omphteliba** [RexDude/navigation_factory#9]
Hi,
ist auch geplant eine Sitemap-Navigation (Kategorien und Artikel) ausgeben zu können? 

![fact-finder_-_fact-finder_-_leader_in_personalised_on-site_search__shop_navigation_and_merchandising](https://cloud.githubusercontent.com/assets/196336/11627607/21ad999a-9cec-11e5-873f-4b67c157f894.png)

**Comment by RexDude** [comment]
Hey,

noch nicht, aber gute Idee. Kann man sicherlich dazubauen. Lässt sich ja jetzt wunderbar erweitern dass ganze :)

**Comment by omphteliba** [comment]
Und du bist sicher das die navigation_factory das nicht schon kann? ;) Wir hatten das ja schonmal...

**Comment by RexDude** [comment]
Echt? Kann mich gar nicht mehr erinnern ;)
Also im Prinzip über setShowAll() bekommt man ja den ganezn Baum. Allerdings wenn dann noch Extra Artikel pro Katageorie vorkommen werden diese allerdings nicht angezeigt.

Ist machmal sehr individuell. Meine letzte Sitemap habe ich mit 2 Nav Objekten gebaut. 1 hat die Hauptnavi ausgegeben die 2. die Footer Navi. Beide uls hab ich dann untereinander gehängt.

**Comment by RexDude** [comment]
Da hier nix mehr passiert schließe ich.
